workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 11
    scripts:
      - name: Generate platform files and clean
        script: | 
          set -e
          flutter create .
          cd android && ./gradlew clean && cd ..
      - name: Build Android App
        script: | 
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
