workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 11
    scripts:
      - name: Setup Project and fix Android version
        script: | 
          set -e
          flutter create .
          # This is a more robust command to find and replace the min sdk version
          sed -i '' 's/minSdkVersion.*/minSdkVersion 21/' android/app/build.gradle
      - name: Build Android App
        script: | 
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
